# Generated by Django 5.2 on 2025-04-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalIncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('father_kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('father_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mother_kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_kra',
            field=models.CharField(default='342', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_kra',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
